# This workflow publishes to GitHub Packages when a release is created
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish to GitHub Packages

on:
  push:
    branches: [master]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
